from __future__ import annotations

import shutil
import uuid
from datetime import datetime, timezone
from pathlib import Path

from context_vault_studio.services.workspace_builder import build_workspace_from_config
from context_vault_studio.storage import (
    REPO_ROOT,
    BUILD_APPLY_RUNS_DIR,
    save_build_apply_run,
)


def _now_iso() -> str:
    return datetime.now(timezone.utc).astimezone().isoformat(timespec="seconds")


def _copy_tree_contents(source: Path, target: Path) -> None:
    if not source.exists():
        return
    for item in source.rglob("*"):
        if item.is_dir():
            continue
        rel_path = item.relative_to(source)
        destination = target / rel_path
        destination.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(item, destination)


def _apply_patch_bundle(preview_dir: Path, patch_bundle: dict, scratch_apply_dir: Path, rollback_dir: Path) -> list[str]:
    changed_paths: list[str] = []
    inputs_dir = preview_dir / "inputs"
    _copy_tree_contents(inputs_dir, rollback_dir)
    _copy_tree_contents(inputs_dir, scratch_apply_dir)

    for entry in patch_bundle.get("file_actions", []):
        action = entry.get("action")
        target_path = entry.get("path", "")
        target = Path(target_path)
        relative_target = target if not target.is_absolute() else Path(target.name)
        scratch_target = scratch_apply_dir / relative_target
        scratch_target.parent.mkdir(parents=True, exist_ok=True)

        preview_text = ""
        for patch in patch_bundle.get("patches", []):
            if patch.get("path") == target_path:
                preview_text = patch.get("preview", "")
                break

        if action == "modify":
            existing = scratch_target.read_text(encoding="utf-8", errors="replace") if scratch_target.exists() else ""
            scratch_target.write_text(
                existing.rstrip() + ("\n\n" if existing.strip() else "") + f"<!-- {preview_text} -->\n",
                encoding="utf-8",
            )
        elif action == "create":
            scratch_target.write_text(f"<!-- generated by deterministic build -->\n{preview_text}\n", encoding="utf-8")
        else:
            continue
        changed_paths.append(relative_target.as_posix())

    return changed_paths


def _rescan_scratch_workspace(run_dir: Path, scratch_apply_dir: Path) -> dict:
    config = {
        "vault_name": "Scratch Apply Preview",
        "output_dir": str(run_dir / "rescan_output"),
        "default_mode": "copy",
        "max_file_size_bytes": 5_000_000,
        "default_exclude": [],
        "default_include": [],
        "access": {
            "allowed_roots": [str(scratch_apply_dir)],
            "blocked_paths": [],
            "blocked_patterns": [],
            "enforce_copy_mode": True,
        },
        "sources": [
            {
                "name": "scratch-apply",
                "category": "Apply Preview",
                "path": str(scratch_apply_dir),
                "include": ["**/*"],
                "exclude": [],
                "mode": "copy",
            }
        ],
    }
    return build_workspace_from_config(config, base_dir=Path(REPO_ROOT), dry_run=True, clean=True)


def apply_build_patch_preview(preview: dict) -> dict:
    preview_id = preview.get("id")
    run_id = f"apply-run-{uuid.uuid4().hex[:8]}"
    run_dir = BUILD_APPLY_RUNS_DIR / run_id
    scratch_apply_dir = run_dir / "scratch_apply"
    rollback_dir = run_dir / "rollback"
    scratch_apply_dir.mkdir(parents=True, exist_ok=True)
    rollback_dir.mkdir(parents=True, exist_ok=True)

    preview_dir = Path(preview["bundle_dir"])
    patch_bundle = (preview.get("contents") or {}).get("patch_bundle") or {}
    task_packet = (preview.get("contents") or {}).get("task_packet") or {}
    task_metadata = task_packet.get("metadata") or {}

    changed_files = _apply_patch_bundle(preview_dir, patch_bundle, scratch_apply_dir, rollback_dir)
    after_result = _rescan_scratch_workspace(run_dir, scratch_apply_dir)

    reconciliation_report = {
        "summary": "Applied the patch bundle into scratch space and rescanned the resulting workspace.",
        "before_snapshot_id": task_packet.get("snapshot_bundle_id"),
        "after_snapshot_id": f"{run_id}-rescan",
        "changed_files": changed_files,
        "notes": [
            f"Before file count: {task_packet.get('scope', {}).get('file_count', 0)}",
            f"After file count: {after_result.get('summary', {}).get('file_count', 0)}",
            f"After edge count: {after_result.get('summary', {}).get('edge_count', 0)}",
        ],
    }
    apply_summary = {
        "preview_id": preview_id,
        "scratch_apply_dir": str(scratch_apply_dir),
        "rollback_dir": str(rollback_dir),
        "changed_file_count": len(changed_files),
        "changed_files": changed_files,
        "rescan_summary": after_result.get("summary", {}),
    }

    record = save_build_apply_run(
        {
            "id": run_id,
            "created_at": _now_iso(),
            "label": f"Apply run for {preview_id}",
            "preview_id": preview_id,
            "scratch_apply_dir": str(scratch_apply_dir),
            "rollback_dir": str(rollback_dir),
            "canvas_id": task_metadata.get("canvas_id"),
            "canvas_label": task_metadata.get("canvas_label"),
            "scope_label": task_metadata.get("scope_label"),
            "selected_file_count": len((task_packet.get("scope") or {}).get("selected_files", [])),
            "reconciliation_report": reconciliation_report,
            "apply_summary": apply_summary,
        }
    )
    payload = {
        **record,
        "reconciliation_report": reconciliation_report,
        "apply_summary": apply_summary,
    }
    return payload
